# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Two Foos Walked into a Bar...
email: jdickey@seven-sigma.com
description: Nothing can possibly go wrong. Nothing can possi... *snap*
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeff_dickey
github_username:  jdickey

future: true # per https://jekyllrb.com/docs/upgrading/2-to-3/#all-my-posts-are-gone-whered-they-go
paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
disqus: jdickeyghpages
theme: minima
# google_analytics: dbyll

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - tmp/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: untitled.set :title, 'Hello, again!'

description: Nothing can possibly go wrong. Nothing can possi... *snap*
author:
  name: Jeff Dickey
  # email: jdickey@seven-sigma.com
  email: jeff_dickey@hotmail.com
  github: jdickey
  twitter: jeff_dickey
  # pinterest: asd123
  linkedin: jdickey
  bio: Software and Web developer. Tamer of deadlines. Enchanter of stakeholders.
  # email_md5: d6d968e5de074e1aeef2ed6b9cc336f9

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate

plugins:
  - jekyll-feed
  - jemoji
